---
# This Playbook would deploy all infrastructure of simfarm service.
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  vars_files:
  - group_vars/all
  roles:
  - common
  tags: infra

- hosts: all
  become: yes
  roles:
  - angstwad.docker_ubuntu
  tags: docker

- hosts: master
  become: yes
  vars_files:
    - group_vars/database
  roles:
    - ANXS.postgresql
  tags: db

- hosts: master
  become: yes
  vars_files:
    - group_vars/apiservers
  roles:
    - nginx
  tags: lb
